openapi: 3.0.0
info:
  title: TICKSOW
  description: |
    API for TICKSOW Quiz Project

    **Basic Auth Credentials:**
    - **Username:** badmin
    - **Password:** bpass@213
  version: 1.0.0

servers:

  - url: http://127.0.0.1:8080/v3
    description: Localhost
  - url: http://localhost:8080/v3
    description: Localhost
  
paths:

  /register:
    $ref: './paths/users/register.yaml'
  
  /resend-email-otp:
    $ref: './paths/users/register.yaml'
  
  /verify-email:
    $ref: './paths/users/register.yaml'
  
  /login:
    $ref: './paths/users/register.yaml'
  
  /dashboard:
    $ref: './paths/users/register.yaml'
  
  /view-game-info/{gameId}:
    $ref: './paths/users/register.yaml'
  
  /game/{gameId}:
    $ref: './paths/users/register.yaml'
  
  /game-question/{gameId}/:
    $ref: './paths/users/register.yaml'
  
  /game-answer: #gameId, gameQuestionId, gameAnswerId
    $ref: './paths/users/register.yaml'
  
  /leaderboard/{gameId}/:
    $ref: './paths/users/register.yaml'
  
  /leaderboard:
    $ref: './paths/users/register.yaml'
  
  /wallet:
    $ref: './paths/users/register.yaml'
  
  /wallet-transactions/{pageNum}/{listPerPage}:
    $ref: './paths/users/register.yaml'
  
  /wallet-topup:
    $ref: './paths/users/register.yaml'
  
  /wallet-withdraw:
    $ref: './paths/users/register.yaml'
  
  /view-profile:
    $ref: './paths/users/register.yaml'
  
  /edit-profile:
    $ref: './paths/users/register.yaml'
  
  /logout:
    $ref: './paths/users/register.yaml'
  
  /customer-service:
    $ref: './paths/users/register.yaml'
  
  /customer-service-messages/{pageNum}/{listPerPage}:
    $ref: './paths/users/register.yaml'

  

  

