openapi: 3.0.0
info:
  title: TICKSOW
  description: |
    API for TICKSOW Quiz Project
  
  version: 1.0.0

servers:

  - url: http://127.0.0.1:8080/v3
    description: Localhost
  - url: http://localhost:8080/v3
    description: Localhost
  
paths:

  /register:
    $ref: './paths/users/register.yaml'
  
  /resend-email-otp:
    $ref: './paths/users/resend-email-otp.yaml'
  
  /verify-email:
    $ref: './paths/users/verify-email.yaml'
  
  /login:
    $ref: './paths/users/login.yaml'
  
  /logout:
    $ref: './paths/users/logout.yaml'
  
  /dashboard:
    $ref: './paths/users/dashboard.yaml'
  
  /view-game-info/{gameId}:
    $ref: './paths/game/view-game-info.yaml'
  
  /game-question/{gameId}/:
    $ref: './paths/game/game-question.yaml'
  
  /game-answer:
    $ref: './paths/game/game-answer.yaml'
  
  /leaderboard:
    $ref: './paths/game/leaderboard.yaml'
  
  /wallet:
    $ref: './paths/wallet/wallet.yaml'
  
  /wallet-transactions/{pageNum}/{listPerPage}:
    $ref: './paths/wallet/wallet-transactions.yaml'
  
  /wallet-topup:
    $ref: './paths/wallet/wallet-topup.yaml'
  
  /wallet-withdraw:
    $ref: './paths/wallet/wallet-withdraw.yaml'
  
  /view-profile:
    $ref: './paths/profile/view-profile.yaml'
  
  /edit-profile:
    $ref: './paths/profile/edit-profile.yaml'
  
  /delete-profile:
    $ref: './paths/profile/delete-profile.yaml'
  
  /customer-service:
    $ref: './paths/customer-service/customer-service.yaml'
  
  /customer-service-messages/{pageNum}/{listPerPage}:
    $ref: './paths/customer-service/customer-service-messages.yaml'
  
  /customer-service-message:
    $ref: './paths/customer-service/customer-service-message.yaml'


components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  

